[package]
name = "lspath"
version = "0.1.3"
authors = ["James Bull <jamesphillipbull@gmail.com>"]
description = "Very basic ls tool for the PATH environment variable."
license = "MIT/Apache-2.0"

[dependencies]
